title: Gil Sousa
author: GitHub User
email: tiagosousafl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! My name is Gil Sousa. Interested in XP, Python, Node, PHP and DevOps. Currently working as software development manager @Flipside. Trying to learn something new every day.

twitter_username: sousatg
github_username:  sousatg

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

collections:
  projects:
    output: true

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- index.md
#- projects.md
#- blog.md

# Build settings
markdown: kramdown
